### ISSUE TITLE
RC for CMSAF SARAH

### ISSUE THREAD

**Issue by Funkensieper** [PCMDI/obs4MIPs-cmor-tables#110]
1) source_name = 'CMSAF-SARAH'
2) release_year = '2017'
3) source_description = 'Surface solAr RAdiation data set - Heliosat. Based on MVIRI/SEVIRI aboard METEOSAT.'
4) source_version_number = '2.0'
5) institution_id = 'DWD'
6) region = 'africa atlantic_ocean europe'
7) source_type = 'satellite_retrieval'

nobs: none
stddev: none
stderr: none

**Comment by gleckler1** [comment]
@Funkensieper   Please confirm this is for downwelling shortwave at the surface, ie., rsds.  Or is it rsns?   Looks like 3 separate domains, correct?   If yes, I think that would fit ODS2.1 if it is provided as a global field, with missing data outside the 3 domains, or perhaps better a subglobal domain which includes the 3.   I suggest this because the DRS/filename structure in ODS2.1 does not include 'region', so if the 3 domains were in separate files they would not be unique.

**Comment by Funkensieper** [comment]
Correct,  it's ``rsds``. The dataset covers everything seen by the geostationary satellite, but cropped at  the edges of the disk (see the first figure [here](http://www.mdpi.com/2072-4292/9/5/429)). I just included multiple regions to make the description more informative. The data is provided on a subglobal grid (lon=[-63:63], lat=[-63:63]) in one file.
